### ISSUE TITLE
How about enable "Github Code Scanning" ?

### ISSUE THREAD

**Issue by HaraShun** [sheepla/pingu#6]
How about enable `Github Code Scanning` ?

![image](https://user-images.githubusercontent.com/2841965/173194287-873471fa-556d-4227-9a87-ea1cef6cfbaf.png)

[Go のコードでも GitHub Code Scanning が使えるらしい | text.Baldanders.info](https://text.baldanders.info/remark/2020/10/github-code-scanning-with-golang/)

[GitHub、コードの脆弱性を検出する「Code Scanning」を全ユーザーに提供 - ZDNet Japan](https://japan.zdnet.com/article/35160321/)

[GitHub、コードの脆弱性などを発見してくれる「GitHub Code Scanning」正式版が提供開始。パブリックリポジトリには無料 － Publickey](https://www.publickey1.jp/blog/20/githubgithub_code_scanning.html)

This only adds one file as below.
https://github.com/HaraShun/pingu/blob/master/.github/workflows/codeql-analysis.yml

And this screen shot is the result of trying to fork and running `Github Code Scanning` at my environment.

![image](https://user-images.githubusercontent.com/2841965/173194385-26ed3415-3be0-446a-937e-70a69c52e077.png)

**Comment by sheepla** [comment]
Wow, I didn't know that GitHub officially had such a feature. 👀 It looks very good so I'll give it a try!

**Comment by sheepla** [comment]
Thank you for your pull request. I've implemented it, so I'll close this issue.✅
